main : AGTHARN\BankUI\Main
name: BankUI
version: 1.0.0
api: 5.0.0
authors: 
- AGTHARN
- Biswajit

permissions:
  bankui.admin:
    description: Permission to view other players bank
    default: op
  bankui.cmd:
    description: Permission to open bank ui
    default: true
  bankui.cmd.top:
    description: Permission to check bank leaderboard
    default: true
